"""
Assemble the final course video from SadTalker output + original TTS audio.

Usage:
    conda activate ai-course
    python 00_pipeline/finalize.py <day> "<title>"

Example:
    python 00_pipeline/finalize.py 001 "Build the Video Pipeline"

Inputs  (must exist before running):
    00_pipeline/talking_heads/day_001_talking_head.mp4   ← download from Colab/Drive
    00_pipeline/audio/day_001.mp3                        ← generated by tts.py

Output:
    00_pipeline/final/day_001_final.mp4
"""

import os
import subprocess
import sys
import tempfile
from PIL import Image, ImageDraw, ImageFont

PIPELINE_DIR = os.path.dirname(os.path.abspath(__file__))

CANVAS_W, CANVAS_H = 1280, 720
FACE_SIZE          = 360
FPS                = 25
BG_COLOR           = (15, 23, 42)       # #0f172a  dark navy
TEXT_WHITE         = (255, 255, 255)
TEXT_MUTED         = (148, 163, 184)    # #94a3b8
TEXT_DIM           = (71, 85, 105)      # #475569

FONT_PATH = "/System/Library/Fonts/Helvetica.ttc"

SECTIONS = {
    range(1,   6):  "Warmup",
    range(6,  21):  "Section 1 · Text AI",
    range(21, 36):  "Section 2 · Automation",
    range(36, 51):  "Section 3 · Data & Analysis",
    range(51, 66):  "Section 4 · Real Apps",
    range(66, 79):  "Section 5 · Vision & Multimodal",
    range(79, 89):  "Section 6 · AI Agents",
    range(89, 101): "Section 7 · Finance & Trading",
}


def section_label(day: int) -> str:
    for rng, label in SECTIONS.items():
        if day in rng:
            return label
    return ""


def load_font(size: int) -> ImageFont.FreeTypeFont:
    try:
        return ImageFont.truetype(FONT_PATH, size)
    except OSError:
        return ImageFont.load_default()


def make_background(day_str: str, title: str, section: str) -> str:
    """Render the full background frame (dark canvas + text) as RGB PNG."""
    img = Image.new("RGB", (CANVAS_W, CANVAS_H), BG_COLOR)
    draw = ImageDraw.Draw(img)

    font_day     = load_font(54)
    font_title   = load_font(26)
    font_section = load_font(17)

    draw.text((60, 46),  f"DAY {day_str}", font=font_day,     fill=TEXT_WHITE)
    draw.text((62, 114), title,            font=font_title,   fill=TEXT_MUTED)
    draw.text((62, 684), f"100 Days of AI  ·  {section}",
              font=font_section, fill=TEXT_DIM)

    tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
    img.save(tmp.name)
    return tmp.name


def get_duration(path: str) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "quiet", "-show_entries", "format=duration",
         "-of", "csv=p=0", path],
        capture_output=True, text=True
    )
    return float(result.stdout.strip())


def run(day_str: str, title: str):
    day_int      = int(day_str)
    talking_head = os.path.join(PIPELINE_DIR, "talking_heads", f"day_{day_str}_talking_head.mp4")
    audio        = os.path.join(PIPELINE_DIR, "audio",         f"day_{day_str}.mp3")
    output       = os.path.join(PIPELINE_DIR, "final",         f"day_{day_str}_final.mp4")

    for path, label in [(talking_head, "Talking head"), (audio, "Audio")]:
        if not os.path.exists(path):
            print(f"Error: {label} not found: {path}")
            sys.exit(1)

    duration   = get_duration(talking_head)
    section    = section_label(day_int)
    bg_png     = make_background(day_str, title, section)

    face_x = (CANVAS_W - FACE_SIZE) // 2
    face_y = (CANVAS_H - FACE_SIZE) // 2

    filt = (
        # Scale talking head with high-quality resampling
        f"[0:v]scale={FACE_SIZE}:{FACE_SIZE}:flags=lanczos[face];"
        # Loop the static background PNG as the base canvas
        f"[2:v]scale={CANVAS_W}:{CANVAS_H}[bg];"
        # Composite talking head onto the pre-rendered background
        f"[bg][face]overlay=x={face_x}:y={face_y}[out]"
    )

    cmd = [
        "ffmpeg", "-y",
        "-i", talking_head,               # 0: talking head video
        "-i", audio,                      # 1: original TTS audio
        "-loop", "1", "-i", bg_png,       # 2: pre-rendered background PNG (with text)
        "-filter_complex", filt,
        "-map", "[out]",
        "-map", "1:a",
        "-c:v", "libx264", "-preset", "slow", "-crf", "18",
        "-c:a", "aac", "-b:a", "192k",
        "-t", str(duration),
        "-movflags", "+faststart",
        output,
    ]

    print(f"Day     : {day_str} — {title}")
    print(f"Section : {section}")
    print(f"Output  : {output}")
    print()

    result = subprocess.run(cmd, capture_output=True, text=True)
    os.unlink(bg_png)

    if result.returncode != 0:
        print("FFmpeg error:")
        print(result.stderr[-3000:])
        sys.exit(1)

    size_mb = os.path.getsize(output) / 1_000_000
    print(f"Done. {output} ({size_mb:.1f} MB)")


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    run(sys.argv[1].zfill(3), sys.argv[2])
